// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srrlzowyoogdbsnokqnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycmx6b3d5b29nZGJzbm9rcW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1ODIyNDcsImV4cCI6MjA5OTE1ODI0N30.n7n5rvTmLiy_EdK7YE5_ecfvtWhg7zU0yv-WgTYu6iU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});